# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_auto_20171008_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='serialId',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
